### ISSUE TITLE
Output directory for made files

### ISSUE THREAD

**Issue by bezgerts** [foliant-docs/foliant#43]
I'm proposing to set output directory for made files in foliant.yml. 

For example:
```
output_directory:
    docx: /out/docx
    pdf: /out/pdf
    html: /out/html
```
