### ISSUE TITLE
Extension proposal: environment variables in config

### ISSUE THREAD

**Issue by Vanderhoof** [foliant-docs/foliant#54]
Create an extension which will allow to refer to environment variables in foliant.yml

Example usage:

```yaml
backend_config:
    confluence:
        host: https://confluence.myteam.ru/
        login: !env FOLIANT_CONFLUENCE_LOGIN
        password: !env FOLIANT_CONFLUENCE_PASSWORD
```
